[nfs]
172.31.84.200 ansible_ssh_user='ec2-user'

[webservers]
172.31.85.165 ansible_ssh_user='ec2-user'
<Web-Server2-Private-IP-Address> ansible_ssh_user='ec2-user'

[db]
172.31.48.6 ansible_ssh_user='ec2-user' 

[lb]
172.31.93.68 ansible_ssh_user='ubuntu'